#cloud-config
users:
  - name: ${uname}
    groups: ${ugroup}
    shell: ${shell}
    sudo: ["${s_com}"]
    ssh_authorized_keys:
      - ${ssh_key}
package_update: true
package_upgrade: false
packages:
  - ${pack}
